project:
  type: website
  output-dir: docs

website:
  title: "Eccology Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - researchthemes.qmd
      - people.qmd

format:
  html:
    theme: sandstone
    #fontcolor: "#56B4E9"
    css: styles.css
    toc: true

editor: visual

